/* AUTO-GENERATED by 08-integration/.../foresight_settle_atomic.ts — a REAL devnet
   transaction where txoracle.validateStatV2 verified the outcome and the Foresight
   grade memo landed atomically in the same tx. */
window.SETTLEMENT_PROOF = {
  "product": "foresight",
  "kind": "atomic-onchain-settlement",
  "network": "devnet",
  "fixtureId": 18241006,
  "seq": 962,
  "statKeys": [
    1,
    2
  ],
  "values": [
    1,
    2
  ],
  "claim": "away win proven on-chain (goals 1-2); grade memo landed in the SAME transaction — the grade exists only because the chain verified the outcome",
  "commitHash": "e756bbe2cdfff5ef6a35691bf5c365f97857683994adc8d2777cdd296d466718",
  "commitTx": "bpxbfCjpcJfuG3Sy5ShrYYFZPXSieE6jMccjG2Ua4xkjJuNhXtW26bJFFEYgc7LjWvuqX5CnvwC4dDQQnvdUAsL",
  "pick": "part2 (Argentina)",
  "result": "WIN",
  "oracleProgram": "6pW64gN1s2uqjHkn1unFeEjAwJkPGHoppGvS715wyP2J",
  "dailyScoresPda": "HJ6nSVkUs4VG9JQ5sEUq3VbmyUSBf76ePXUCATLtRYTX",
  "epochDay": 20649,
  "memo": "FSGHT1-SETTLE|e756bbe2cdfff5ef6a35691bf5c365f97857683994adc8d2777cdd296d466718|fx18241006|pick=part2(Argentina)|goals=1-2|result=WIN|gate=validateStatV2@sameTx|commitTx=bpxbfCjpcJfuG3Sy5ShrYYFZPXSieE6jMccjG2Ua4xkjJuNhXtW26bJFFEYgc7LjWvuqX5CnvwC4dDQQnvdUAsL",
  "txSig": "3ukg95uA2cipKZA5yhuU3ZfYT4G8FYMTjxggM1JLXFsfjxKvhMMFkXpzCAF84QzYHGDaSv3LED4bpz2jJRT1Wybt",
  "explorer": "https://explorer.solana.com/tx/3ukg95uA2cipKZA5yhuU3ZfYT4G8FYMTjxggM1JLXFsfjxKvhMMFkXpzCAF84QzYHGDaSv3LED4bpz2jJRT1Wybt?cluster=devnet",
  "settledAt": "2026-07-19T00:33:19.948Z"
};
